# Generated by Django 2.2.1 on 2020-02-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_pan_no', models.CharField(max_length=200)),
                ('emp_age', models.CharField(max_length=200)),
                ('emp_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('emp_email', models.CharField(max_length=200)),
                ('emp_city', models.CharField(choices=[('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Other', 'Other')], max_length=200)),
            ],
        ),
    ]
