# Generated by Django 2.2.1 on 2020-02-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0002_auto_20200208_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=254),
        ),
    ]
