# Generated by Django 2.2.1 on 2020-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0003_auto_20200208_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(max_length=254),
        ),
    ]
