# Generated by Django 2.2.1 on 2020-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0006_auto_20200208_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_age',
            field=models.IntegerField(max_length=254),
        ),
    ]
