# Generated by Django 2.2.1 on 2020-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0008_auto_20200211_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=200),
        ),
    ]
