# Generated by Django 2.2.1 on 2020-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0011_auto_20200211_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_pan_no',
            field=models.CharField(max_length=200),
        ),
    ]
