# Generated by Django 2.2.1 on 2020-02-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0012_auto_20200211_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=200, verbose_name="Member's name"),
        ),
    ]
