# Generated by Django 2.2.1 on 2020-02-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_Master', '0013_auto_20200217_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=200),
        ),
    ]
